### ISSUE TITLE
error: comparison between pointer and zero character constant

### ISSUE THREAD

**Issue by loust** [DinoTools/liblcfg#1]
I was trying to install it under Arch using this tutorial:
https://www.dinotools.de/en/2016/02/06/how-to-install-dionaea-on-arch-linux/

When I got to the point where I ran `yaourt -S dionaea-git`, it was working fine until I got to installing liblcfg.

Note, I am testing this in a vagrant arch box `terrywang/archlinux`

Here is where the error occurs:

```
Making all in tools
make[2]: Entering directory '/tmp/yaourt-tmp-vagrant/aur-liblcfg-git/src/liblcfg-git/code/tools'
gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I ../.. -Werror -Wall -g -D_FORTIFY_SOURCE=2 -D _GNU_SOURCE -I/usr/local/include -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -MT lcfg.o -MD -MP -MF .deps/lcfg.Tpo -c -o lcfg.o lcfg.c
lcfg.c: In function ‘main’:
lcfg.c:134:13: error: comparison between pointer and zero character constant [-Werror=pointer-compare]
     if( key == '\0' )
             ^~
lcfg.c:134:9: note: did you mean to dereference the pointer?
     if( key == '\0' )
         ^
cc1: all warnings being treated as errors
make[2]: *** [Makefile:402: lcfg.o] Error 1
make[2]: Leaving directory '/tmp/yaourt-tmp-vagrant/aur-liblcfg-git/src/liblcfg-git/code/tools'
make[1]: *** [Makefile:407: all-recursive] Error 1
make[1]: Leaving directory '/tmp/yaourt-tmp-vagrant/aur-liblcfg-git/src/liblcfg-git/code'
make: *** [Makefile:339: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build liblcfg-git.
```

Thank you.

**Comment by phibos** [comment]
I'm sorry but the dionaea-git package in the AUR is deprecated and the lcfg library has been replaced in dionaea 0.4 released in 2016. For more information have a look at the Changelog [0.4.0 - 2016-05-31](https://github.com/DinoTools/dionaea/blob/master/CHANGELOG.rst#040---2016-05-31)

I'm not aware of any project using this library. So bugs wont be fixed.
